#ifndef CONSTANTS_H
#define CONSTANTS_H

#define INITIAL_FOOD_SPAWN_RATE 0.07f
#define FOOD_SPAWN_RATE 0.0004f
#define INITIAL_CREATURE_ENERGY 1
#define COST_OF_LIVING 0.01f
#define INITIAL_CREATURE_N 64
#define MAX_CREATURE_N 1024 * 1024 * 2
#define MAX_PARAMETER_VALUE 5.0f

#define BIT_FOOD 0
#define BIT_CREATURE 1

#endif

