#ifndef CONSTANTS_H
#define CONSTANTS_H

// #define INITIAL_FOOD_SPAWN_RATE 0.07f
// #define FOOD_SPAWN_RATE 0.0004f
// #define INITIAL_CREATURE_ENERGY 1
// #define COST_OF_LIVING 0.01f
// #define INITIAL_CREATURE_N 64

// #define MAX_PARAMETER_VALUE 5.0f

#define WIDTH 1024
#define HEIGHT 1024

#define MAX_CREATURE_N (1 << 19)

#define SENSORS_N 32
#define HIDDEN_N 32
#define ACTIONS_N 32
#define ACTION_TYPES_N 4


#define SENSOR_STDDEV 1.0f
#define ACTION_STDDEV 1.0f

#define SENSORS_MUTATION_PACE 3
#define PARAMETER_MUTATION_STDDEV 0.1f
#define ACTIONS_MUTATION_PACE 3


#define MOVE_ACTION 0
#define EAT_ACTION 1
#define ATTACK_ACTION 2
#define REPRODUCE_ACTION 3


#define ENERGY_DECAY 0.02f
#define FOOD_SPAWN_QUANTITY 1024


#endif

